# App Keepers internals envs
application:
  containerName: 'keeper-svc'
  containerPort: 1323
  env: 'development'

  # Application Metadata
  meta:
    name: 'keeper-service'
    namespace: 'keeper-namespace'
    appName: 'keeper'
    tier: 'backend'

  # Application Configurations
  config:
    replicas: 1
    restartPolicy: 'Always'
    imagePullPolicy: 'Never'
    image: 'keeper-service:local'

  # Resource configuration
  resources:
    requests:
      memory: '512Mi'
      cpu: '256m'
    limits:
      memory: '512Mi'
      cpu: '256m'

  # Application Secrets
  secrets:
    name: 'keeper-secrets'

  # Application Database Secrets
  database:
    host: 'keeper-pg-cluster-rw'
    port: 5432
    db_name: 'keeper'
    user: 'postgres'
    pass: 'postgres'

  # Authentication Secrets
  authentication:
    jwtSecret: 'my-super-protected-and-complex-jwt-secret'
    jwtCookieDomain: 'localhost'

  # OpenTelemetry and Signoz Secrets
  opentelemetry:
    serviceName: 'keeper-dev'
    insecureMode: true
    otelExporterOtlpEndpoint: 'signoz-apm-otel-collector.platform.svc.cluster.local:4317'

# Postgres Deployment
database:
  namespace: 'keeper-namespace'
  cluster:
    name: 'keeper-pg-cluster'
    instances: 1