definitions:
  ResponseError:
    properties:
      message:
        type: string
    type: object
  ResponseOk:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/liveness:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseOk'
      summary: Liveness endpoint
      tags:
      - Misc
  /v1/readiness:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Readiness endpoint
      tags:
      - Misc
  /v1/version:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Get version of keeper application
      tags:
      - Misc
swagger: "2.0"
