version: '2'
services:
  keeper-postgres:
    container_name: keeper_database
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - keeper-postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  keeper-postgres-volume: {}
