apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.secrets.name }}
  namespace: {{ .Values.application.meta.namespace }}
type: Opaque
stringData:
  ENV: {{ .Values.application.env }}
  SERVER_PORT: "{{ .Values.application.containerPort }}"

  # App Database Config
  DB_HOST: {{ .Values.application.database.host }}
  DB_PORT: "{{ .Values.application.database.port }}"
  DB_NAME: {{ .Values.application.database.db_name }}
  DB_USER: {{ .Values.application.database.user }}
  DB_PASS: {{ .Values.application.database.pass }}

  # Authentication
  JWT_SECRET: {{ .Values.application.authentication.jwtSecret }}
  JWT_COOKIE_DOMAIN: {{ .Values.application.authentication.jwtCookieDomain }}
